name: CICHANG REMEMBER 

on:
  workflow_dispatch:
    inputs:
      message:
        description: "message"
        required: false


env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  OPENAI_API_BASE: ${{ secrets.OPENAI_API_BASE }}

jobs:
  sync:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: install python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip" # caching pip dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      
      - name: GET UP WITH WORDS
        run: |
          python cichang.py ${{ secrets.HJ_USERNAME }} ${{ secrets.HJ_PASSWORD }} ${{ secrets.HJ_TOKEN }} --tele_token ${{ secrets.TG_TOKEN }} --tele_chat_id ${{ secrets.TG_HJ_CHAT_ID }}
    
      - name: My PR stats
        env:
          GITHUB_TOKEN: ${{ secrets.G_T}}
        run: |
          python pr.py 
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add . 
          git commit -m "generated today stats" || echo "no need to commit "
          git push || echo "no file change"
 